#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/ceasar/data/users/" ]; then
	exit
fi

# Prevent running and causes issues with outdated ceasar version
if ! id "ceasarweb" &> /dev/null; then
	exit
fi

# Check if preinstall hook exists
if [ -e "/etc/ceasar/hooks/php/pre_install.sh" ]; then
	/etc/ceasar/hooks/php/pre_install.sh
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$CEASAR" ]; then
	export CEASAR='/usr/local/ceasar'
	PATH=$PATH:/usr/local/ceasar/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/ceasar/func/main.sh
source /usr/local/ceasar/func/upgrade.sh
source /usr/local/ceasar/conf/ceasar.conf
source /usr/local/ceasar/install/upgrade/upgrade.conf

# Restart ceasar service
if [ -f "/etc/init.d/ceasar" ]; then
	systemctl restart ceasar > /dev/null 2>&1
fi

# Check if preinstall hook exists
if [ -e "/etc/ceasar/hooks/php/post_install.sh" ]; then
	/etc/ceasar/hooks/php/post_install.sh
fi
