#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/ceasar/data/users/" ]; then
	exit
fi

if ! id "ceasarweb" &> /dev/null; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$CEASAR" ]; then
	export CEASAR='/usr/local/ceasar'
	PATH=$PATH:/usr/local/ceasar/bin
	export PATH
fi

# Load runtime functions and variables
source /usr/local/ceasar/func/main.sh
source /usr/local/ceasar/conf/ceasar.conf

# Restart ceasar-web-terminal service if enabled
if [ -f "/etc/systemd/system/ceasar-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled ceasar-web-terminal > /dev/null 2>&1; then
		systemctl restart ceasar-web-terminal
	fi
fi
